### ISSUE TITLE
Support STAC Collections as Job Results

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/PSC#10]
## Background

For Batch Jobs, the results get returned by the API as a single STAC Item. This was meant to make implementations easier as you only need to read a single response and not follow any (STAC) links to get all results. While this is easy to implement, it is too simple for some use cases where the metadata is important. This applies, for example, for the CARD4L use cases in openEO Platform. There you need to expose a STAC catalog with  multiple Items and specific metadata. This is not possible with the current approach.

## Proposal

Therefore, I made an attempt to introduce and allow STAC Collections as a potential response in PR https://github.com/Open-EO/openeo-api/pull/359. As the most important part for downloading is the object key "assets" in both an Item and a Collection, the specs are somewhat easy to use without breaking too much. So the idea is to expose a STAC Collection and duplicate the Item Assets into Collection Assets, for now, to have the assets available to all clients in a somewhat backward-compatible way.
The important bit of the change is described [here](https://github.com/Open-EO/openeo-api/pull/359/files/954416cbca6d9187a7de0f8d6ca33ebcf52ea6bb#diff-d910ba2ef878f7db0223a966b81c8b3f3b65027bb39e4431bb05140171eece39R2906-R2924). 

Due to the same field name, I have checked the client implementations to see whether they rely on anything except assets to be returned by the API. The result is pretty promising:

JS Client: (✔) getResultsAsItem will return something not very meaningful metadata in JS client < v1.1.0, but it still returns the assets. Other methods work smoothly and JS Client >= v1.1.0 already supports Collections natively.
Web Editor: ✔ Works smoothly
R Client: ✔ Works smoothly - it uses properties.expires, but it's implemented in a way that it ignores it if not set.
Demo App: ✔ Works smoothly
Python client: ✔ Works smoothly

That means, although the proposal is a breaking change, nothing in the clients breaks and servers don't need to implement it if they don't have a use case for it.

Therefore, I propose to merge PR https://github.com/Open-EO/openeo-api/pull/359 and release it once we decide to release openEO API 1.1.

## Additional context

Once we release an openEO API 2.0, the assets would be removed from the Collection Assets.

The PR also updates to the latest STAC version.

Deadline: 06.05.2021

**Comment by m-mohr** [comment]
+1

**Comment by mkadunc** [comment]
+1

**Comment by lforesta** [comment]
+1

**Comment by edzer** [comment]
+1

**Comment by aljacob** [comment]
+1

**Comment by neteler** [comment]
+1

**Comment by m-mohr** [comment]
@jdries Something for you to review after your vacation. :-)

Thanks all for the votes.

**Comment by jdries** [comment]
+1

**Comment by m-mohr** [comment]
Accepted by all, thanks! Will get merged.
