### ISSUE TITLE
Leaving the PSC

### ISSUE THREAD

**Issue by lforesta** [Open-EO/PSC#17]
Hi all, sadly I think I need to leave my spot on the PSC.

Although I always follow the project and am still a strong advocate for it, I've not had any time for it in the last few months, and likely in the next few too. I think that someone else more involved in the project should have the chance to step in instead.

**Comment by m-mohr** [comment]
Hi @lforesta,

sad to hear this, but I think everyone can understand this. I've removed you from the list of PSC members and will bring this up in the next/first PSC meeting so that we can find a successor. Whishing you all the best for the future!

**Comment by m-mohr** [comment]
We'll leave this seat open for now and see what the future brings. Maybe we can identify someone from EODC and/or other organizations to become part of the PSC.
