### ISSUE TITLE
New PSC member nominated: Benjamin Schumacher (EODC)

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/PSC#19]
## Background

Christian Briese (EODC) has nominated a new PSC member. According to the PSC guidelines we need to have an official PSC vote. As usual, please vote with +1, +0, 0, -0 or -1.

## Proposal

It is proposed to add **Benjamin Schumacher** (EODC) to the openEO PSC as a new member.
The proposal did not contain any additional information about the nominee.

Deadline: October 6th, 2022

**Comment by m-mohr** [comment]
Personally, I have some concerns about the level of experience Benjamin has with openEO. Some discussions and votes require a good understanding and practical experience with openEO (esp. API and processes). I'll cast my vote later.

**Comment by mkadunc** [comment]
+1

**Comment by m-mohr** [comment]
A gentle reminder to cast your votes. @aljacob @jdries @edzer @neteler

**Comment by edzer** [comment]
+1

**Comment by jdries** [comment]
+1

**Comment by neteler** [comment]
Not knowing Benjamin well, +0

**Comment by m-mohr** [comment]
Good points, @jdries. I could talk to Christian today at the interTwin meeting.

**Comment by aljacob** [comment]
-1 I personally would prefer someone with a more technical background, who can actually comment and bring in new technical competences.

**Comment by m-mohr** [comment]
I'll go with -0 for now having the reasons from @jdries in mind.

The result is: 
2x accept
3x neutral (including +/- tendencies)
1x reject / veto

As we have a veto, I'd like to bring the PSC guidelines to mind again:

> - Respondents may vote -1 to veto a proposal, but must provide clear reasoning and alternate approaches to resolving the problem [...]
> - A proposal will be accepted if it receives +3 (including the proposer) and no vetoes (-1) or has not received enough votes in 20 business days.
> - If a proposal is vetoed, and it cannot be revised to satisfy all parties, then it can be resubmitted for an override vote in which a majority of all eligible voters indicating +1 is sufficient to pass it. Note that this is a majority of all committee members, not just those who actively vote.

So we can now further discuss and change votes until the deadline is met. If nothing changes until then, the nomination is rejected. A resubmission would currently not lead to a majority.

**Comment by aljacob** [comment]
changing my vote +0 after further discussion, I still think a technical person, would be the best, but I can also see that it makes sense to support the community and user side, and for that role Benjamin is a good choice.

**Comment by m-mohr** [comment]
This vote will end at the end of this day.

I just went through this and we actually have the following votes:
2x +1 
4x 0 (including -0, 0 and +0)
0x -1

I just realized today that although Alex changed his vote, **the proposal would still be rejected**. We don't have a veto anymore, but still not 3 +1's:

> A proposal will be accepted if it receives +3 (including the proposer) and no vetoes (-1) or has not received enough votes in 20 business days.

**Comment by jdries** [comment]
After discussion in PSC, (and comment above), I'm changing to +1.
As indicated, the primary argument for having a technical representative (for me) is to be able to protect the interests of a given backend/company. I think we made that point, and should just work under the assumption that the EODC backend is represented by whoever is proposed, also in technical matters. It would be worse to reject a proposal and have no representation at all.
Note that this PSC also works through github issues which can be followed up and commented on by anyone, also without voting rights.

**Comment by m-mohr** [comment]
The proposal has been accepted, thanks!
Welcome to the PSC @bschumac.

**Comment by bschumac** [comment]
Thank you!
