### ISSUE TITLE
Submit openEO as a community standard to OGC

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/PSC#26]
## Background

In #24 we decided to submit the openEO specifications to the OGC as a community standard.
In the meantime we also reached out to various organizations that are OGC members and are (potential) users of openEO and got a lot of supporting letters. All the supporting organizations are listed in #25.

## Proposal

In #25 the justification document for openEO as an OGC community standard has been drafted. Some questions came up and have been solved in the meantime, including a request to OGC for clarification. It clarifies that Intelectual Property Rights can stay with the openEO community and that the PSC will still steer the specifications, no OGC SWG will be founded for openEO.

> 1. IPR: if the spec is open source, then note that  fact on the submission, but check the box that the spec IPR will reside with the contributors (that way OGC does not take the IPR).
> 
> 2. PSC: the presumption for a Community Standard is that the group who maintains the spec will continue to do so. We won’t form a SWG and the openEO PSC can do revisions as needed. We do prefer that periodically, those revisions come to OGC as updates to the Community Standard.

Please read the document in #25 and propose changes if required. Once you agree with the document, please vote here.

Deadline: 06.12.2023 (I'll leave this open until the next PSC meeting on the given day where we can finalize the submission.)

**Comment by mkadunc** [comment]
:+1:

**Comment by aljacob** [comment]
+1

**Comment by bschumac** [comment]
+1

**Comment by edzer** [comment]
+1

**Comment by neteler** [comment]
+1

**Comment by jdries** [comment]
+1

**Comment by m-mohr** [comment]
Accepted.
