### ISSUE TITLE
Exception for review process (JS libraries)

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/PSC#5]
## Background
I am maintaining a number of repositories, which have more than two dependants and thus need a review process with at least two reviews according to the PSC process. The issue is, most dependants are only maintained by me and I can't review myself in the GH review process.

The following repositories are affected;
- js-commons (dependants: js-client, vue-components, processes-docgen, js-processgraphs, web-editor, hub, earthengine-driver)
- js-client (dependants: mobile app, web-editor)
- js-processgraphs (dependants: hub, earthengine-driver, web-editor)
- vue-components (dependants: hub, web-editor, jupyterlab-widgets)

For each of the repositories there's only one additional maintainer that is regularly maintaining a dependant:
For all repositories except the js-client it is @christophfriedrich (who maintains the hub).
For the js-client it is @jneijt (who maintains the mobile app).
The earthengine driver also has contributions by @claxn and @bgoesswe, but on an unsteady basis and they never work with the dependencies themself, but work on other parts of the project.

I would expect that @christophfriedrich will do all the reviews as @jneijt may have no time for openEO after the funding period of the project ends. Christoph is unfortunately just employed on a student assistant basis for low amount of hours per week so reviews could come in rather late. Therefore I'd like to ask if you know any other person that can review JavaScript related changes?

## Proposal
I request to allow an exception for the repositories listed above to only require a single approval for merging breaking changes to master/main. 

## Additional context
Other repositories that might be affected as they have 2+ dependants: python-client, processes-python, pg-parser-python (cc @jdries @claxn)

Deadline: 05.11.2020

**Comment by m-mohr** [comment]
+1

**Comment by edzer** [comment]
+1

**Comment by jdries** [comment]
+

**Comment by m-mohr** [comment]
We have now reached +3, which means without any veto by 13.10.2020 the proposal will be accepted.

**Comment by lforesta** [comment]
+1 for the record

**Comment by aljacob** [comment]
+1

**Comment by neteler** [comment]
+1

**Comment by m-mohr** [comment]
The proposal has been accepted according to the PSC guidelines, thank you!
