### ISSUE TITLE
Communication channels

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/PSC#9]
## Background
Several communication channels will be made inactive in the next months as Matthias Schramm sent around today via the openeo.development mailing list. Also, EODC mentioned last year that they plan to disable the RocketChat.

## Proposal
I propose the following changes to keep things running:

1. Merge PR #3: It changes the wording in the PSC charter as follows: 
    > ~Any member of the openEO mailing list~ **Anyone** may nominate someone for committee membership at any time. 
    
    Question: Is this too broad? We could also say something like "any contributor to the openEO ecosystem".
2. Replace the RocketChat with https://gitter.im/Open-EO/community
3. Replace the external email list openeo@lists.tuwien.at with openeo.psc@uni-muenster.de, which will be redirected to me. We can also think about an alternative that reaches more or all PSC members, if you think that would be better.
4. Delete (or takeover if anyone wants to manage it) the LinkedIn group we have for openEO: https://www.linkedin.com/groups/8694624/

## Additional context

Deadline: 26.02.2021

**Comment by m-mohr** [comment]
+1

**Comment by jdries** [comment]
+1

**Comment by aljacob** [comment]
I'd recommend to use your option to include the "any contributor ...". With the inclusion +1

**Comment by m-mohr** [comment]
@aljacob We could phrase it as follows:

> Anyone with a contribution to the [openEO organization](https://github.com/Open-EO) may nominate someone for committee membership at any time.

**Comment by aljacob** [comment]
sounds good to me

**Comment by m-mohr** [comment]
PSC members, please give an indication which you'd prefer:

1. > Anyone

or 

2. > Anyone with a contribution to the openEO organization

**Comment by edzer** [comment]
+1, favoring "Anyone with a contribution to the openEO organization"

**Comment by mkadunc** [comment]
+1
I support both options (anyone vs. contributors), so I abstain from voting on that part.

**Comment by neteler** [comment]
+1, favoring "Anyone with a contribution to the openEO organization" to reduce the risk of an unfriendly take-over.

**Comment by lforesta** [comment]
+1, I also favor "Anyone with a contribution to the openEO organization"

**Comment by m-mohr** [comment]
Accepted, thank you.
